<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="C1.DataCollection" Version="9.0.20251.213" />
    <PackageReference Include="C1.DataCollection.BindingList" Version="9.0.20251.213" />
    <PackageReference Include="C1.Excel" Version="9.0.20251.144" />
    <PackageReference Include="C1.Win" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.Command" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.FlexGrid" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.FlexGrid.ImportExport" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.Input" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.SplitContainer" Version="8.0.20251.708" />
    <PackageReference Include="C1.Win.SuperTooltip" Version="8.0.20251.708" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartGrid\SmartGrid.csproj" />
  </ItemGroup>

</Project>