<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="C1.Excel" Version="5.0.20231.18" />
    <PackageReference Include="C1.Win.Command" Version="6.0.20231.596" />
    <PackageReference Include="C1.Win.FlexGrid" Version="6.0.20231.596" />
    <PackageReference Include="C1.Win.FlexGrid.ImportExport" Version="6.0.20231.596" />
    <PackageReference Include="C1.Win.Input" Version="6.0.20231.596" />
    <PackageReference Include="C1.Win.SuperTooltip" Version="6.0.20231.596" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SumForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
